create table public.usr (
    id int8 generated by default as identity,
    active boolean not null,
    address varchar(255),
    email varchar(255) not null,
    name varchar(255),
    password varchar(255) not null,
    phone varchar(255),
    username varchar(255) not null,
    primary key (id));

alter table if exists public.usr
    add constraint user_user_fk unique (email);

create table user_role (
    user_id int8 not null,
    roles varchar(255));

alter table if exists user_role
 add constraint user_role_user_fk
 foreign key (user_id) references public.usr

